export interface MCCCode {
  code: string
  description: string
}

export const MCC_CODES: MCCCode[] = [
  { code: '742', description: 'Veterinary Services' },
  { code: '763', description: 'Agricultural Cooperatives' },
  { code: '780', description: 'Landscaping and Horticultural Services' },
  { code: '1520', description: 'General Contractor/Residential Building; Roof, Siding, and Sheet Metal Work Contractors' },
  { code: '4457', description: 'Boat Rentals and Leasing' },
  { code: '4468', description: 'Marinas, Marine Service, and Supplies' },
  { code: '5072', description: 'Hardware, Equipment and Supplies' },
  { code: '5074', description: 'Plumbing and Heating Equipment and Supplies' },
  { code: '5111', description: 'Stationery, Office Supplies, Printing and Writing Paper' },
  { code: '5131', description: 'Piece Goods, Notions, and Other Dry Goods' },
  { code: '5137', description: "Men's, Women's, and Children's Uniforms and Commercial Clothing" },
  { code: '5193', description: 'Florist Suppliers, Nursery Stock & Flowers' },
  { code: '5198', description: 'Paints, Varnishes and Supplies' },
  { code: '5200', description: 'Home Supply Warehouse Stores' },
  { code: '5211', description: 'Lumber and Building Materials Stores' },
  { code: '5231', description: 'Glass, Paint, and Wallpaper Stores' },
  { code: '5251', description: 'Hardware Stores' },
  { code: '5261', description: 'Nurseries and Lawn and Garden Supply Stores' },
  { code: '5300', description: 'Wholesale Clubs' },
  { code: '5310', description: 'Discount Stores' },
  { code: '5311', description: 'Variety Stores' },
  { code: '5399', description: 'Miscellaneous General Merchandise' },
  { code: '5411', description: 'Grocery Stores & Supermarkets' },
  { code: '5422', description: 'Freezer and Locker Meat Provisioners (Butcher Shops)' },
  { code: '5441', description: 'Candy, Nut, & Confectionery Stores' },
  { code: '5451', description: 'Dairy Products Stores (Cheese Shops)' },
  { code: '5462', description: 'Bakeries' },
  { code: '5499', description: 'Misc Food Stores' },
  { code: '5532', description: 'Automotive Tire Stores' },
  { code: '5533', description: 'Automotive Parts and Accessories Stores' },
  { code: '5541', description: 'Service Stations (With or without Ancillary Services)' },
  { code: '5542', description: 'Automated Fuel Dispensers' },
  { code: '5611', description: "Men's and Boys' Clothing and Accessories Stores" },
  { code: '5621', description: "Women's Ready-To-Wear Stores" },
  { code: '5631', description: "Women's Accessory and Specialty Shops" },
  { code: '5641', description: "Children's and Infants' Wear Stores" },
  { code: '5651', description: 'Family Clothing Stores' },
  { code: '5655', description: 'Sports and Riding Apparel Stores' },
  { code: '5661', description: 'Shoe Stores' },
  { code: '5681', description: 'Furriers and Fur Shops' },
  { code: '5691', description: "Men's & Women's Clothing Stores" },
  { code: '5697', description: 'Tailors, Seamstresses, Mending, and Alterations' },
  { code: '5698', description: 'Wig and Toupee Stores' },
  { code: '5699', description: 'Miscellaneous Apparel and Accessory Shops' },
  { code: '5712', description: 'Furniture, Home Furnishings, and Equipment Stores, except Appliances' },
  { code: '5713', description: 'Floor Covering Stores' },
  { code: '5714', description: 'Drapery, Window Covering, and Upholstery Stores' },
  { code: '5718', description: 'Fireplace, Fireplace Screens and Accessories Stores' },
  { code: '5719', description: 'Miscellaneous Home Furnishing Specialty Stores' },
  { code: '5722', description: 'Household Appliance Stores' },
  { code: '5732', description: 'Electronics Stores' },
  { code: '5733', description: 'Music Stores - Musical Instruments, Pianos, and Sheet Music' },
  { code: '5734', description: 'Computer Software Stores' },
  { code: '5735', description: 'Record Stores' },
  { code: '5811', description: 'Catering' },
  { code: '5812', description: 'Restaurants/ Eating Places' },
  { code: '5813', description: 'Bar/Nightclub (>50% Alcohol)' },
  { code: '5814', description: 'Fast Food' },
  { code: '5921', description: 'Package Stores - Beer, Wine, and Liquor' },
  { code: '5931', description: 'Used Merchandise and Secondhand Stores' },
  { code: '5932', description: 'Antique Shops - Sales, Repairs, and Restoration Services' },
  { code: '5940', description: 'Bicycle Shops - Sales and Service' },
  { code: '5941', description: 'Sporting Goods Stores' },
  { code: '5942', description: 'Book Stores' },
  { code: '5944', description: 'Jewelry, Watch, Clock, and Silverware Stores' },
  { code: '5945', description: 'Hobby, Toy, and Game Stores' },
  { code: '5947', description: 'Gift Shop' },
  { code: '5949', description: 'Sewing, Needlework, Fabric & Piece Goods Stores' },
  { code: '5970', description: 'Artist Supply and Craft Stores' },
  { code: '5973', description: 'Religious Goods Stores' },
  { code: '5977', description: 'Cosmetic Stores' },
  { code: '5992', description: 'Florists' },
  { code: '5993', description: 'Cigar Stores and Stands' },
  { code: '5995', description: 'Pet Shops (Food, Supplies)' },
  { code: '5999', description: 'Miscellaneous & Specialty Retail Stores' },
  { code: '7210', description: 'Laundry, Cleaning, and Garment Services' },
  { code: '7216', description: 'Dry Cleaners' },
  { code: '7217', description: 'Carpet and Upholstery Cleaning' },
  { code: '7230', description: 'Barber/Beauty Shops' },
  { code: '7251', description: 'Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops' },
  { code: '7298', description: 'Health and Beauty Spas' },
  { code: '7349', description: 'Cleaning, Maintenance, and Janitorial Services' },
  { code: '7394', description: 'Equipment, Tool, Furniture, and Appliance Rental and Leasing' },
  { code: '7531', description: 'Automotive Body Repair Shops' },
  { code: '7535', description: 'Automotive Paint Shops' },
  { code: '7538', description: 'Automotive Service Shops (Non-Dealer)' },
  { code: '7542', description: 'Car Washes' },
  { code: '7622', description: 'Electronics Repair Shops' },
  { code: '7629', description: 'Electrical and Small Appliance Repair Shops' },
  { code: '7631', description: 'Watch, Clock and Jewelry Repair' },
  { code: '7932', description: 'Billiard and Pool Establishments' },
  { code: '7933', description: 'Bowling Alleys' },
  { code: '7991', description: 'Wineries, Tourist Attractions and Exhibits' },
  { code: '7992', description: 'Public Golf Courses (pro shops)' },
  { code: '7993', description: 'Video Amusement Game Supplies' },
  { code: '7994', description: 'Arcades' },
  { code: '7996', description: 'Amusement Parks, Circuses, Carnivals, and Fortune Tellers' },
  { code: '7997', description: 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses' },
  { code: '7998', description: 'Aquariums, Seaquariums, Dolphinariums, and Zoos' },
  { code: '8062', description: 'Hospitals *gift shops' },
]
